version: 2.1
orbs:
  slack: circleci/slack@4.12.1
# Define the jobs we want to run for this project
jobs:
#Job for building frontend 
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd ./frontend
            npm i
            npm run bu99ild
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - slack/notify:
          branch_pattern: .+
          event: fail
          channel: C04TCCU6M7Z
          template: basic_fail_1

#Job for building backend  

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd ./backend
            npm i
            npm run buil99d
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

#Job for testing frontend            
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # Restore from cache
      - restore_cache:
          key: frontend-build      
      # Your job code here
      - run:
          name: test frontend
          command: |
            cd frontend
            npm i
            npm run test     
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [backend-build]
      # Your job code here
      - run:
          name: test backend
          command: |
            # Your code here
            cd backend
            npm i
            npm run test


# add anlyze phase : scan front-end 

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          key: frontend-build
      # Your job code here
      - run:
          name: scan frontend vulnerability
          command: |
            # Your code here
            cd frontend
            npm i
            npm audit fix --audit-level=critical --force


# add anlyze phase : scan back-end 
  scan-backend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          key: backend-build
      # Your job code here
      - run:
          name: scan backend vulnerability
          command: |
            # Your code here
            cd backend
            npm i
            npm audit fix --audit-level=critical --force
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]

